services:
  engine:
    container_name: engine
    network_mode: host
    build:
      context: .
      dockerfile: service/Dockerfile

  mdp:
    container_name: mdp
    network_mode: host
    build:
      context: .
      dockerfile: mdp/Dockerfile
